### ISSUE TITLE
Practica Hilos Consola

### ISSUE THREAD

**Issue by EvelynLopezz** [SistemasTecTlaxiaco/practica-de-hilos-EvelynLopezz#3]
[Hilo Consola.zip](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-EvelynLopezz/files/8567794/Hilo.Consola.zip)

**Comment by magaly1311** [comment]
*CALIFICACIÓN  DE EVELYN*

portada  25puntos
Procedimiento   25puntos 
Figuras y ilustraciones  17 puntos 
Conclusión 15 puntos 
Total = 82 puntos  = 16.4 % calificación final

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by EvelynLopezz** [comment]
[HILO CONSOLA SUGEY.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-EvelynLopezz/files/8954391/HILO.CONSOLA.SUGEY.pdf)

**Comment by Heidi-19** [comment]
Calificación hilo consola Evelyn: 19.7%
